//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_table
    {
        public int id_admin { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string e_mail { get; set; }
    }
}
