//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<actor_film_table> actor_film_table { get; set; }
        public virtual DbSet<actor_table> actor_table { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<comment_table> comment_table { get; set; }
        public virtual DbSet<film_table> film_table { get; set; }
        public virtual DbSet<genere_table> genere_table { get; set; }
        public virtual DbSet<music_creator_table> music_creator_table { get; set; }
        public virtual DbSet<other_language_table> other_language_table { get; set; }
        public virtual DbSet<photos_table> photos_table { get; set; }
        public virtual DbSet<producer_table> producer_table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vote_table> vote_table { get; set; }
        public virtual DbSet<writers_table> writers_table { get; set; }
        public virtual DbSet<admin_table> admin_table { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
    }
}
