//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class music_creator_table
    {
        public music_creator_table()
        {
            this.film_table = new HashSet<film_table>();
        }
    
        public int id_music_creator { get; set; }
        public string music_creator_name { get; set; }
        public string music_creator_surname { get; set; }
    
        public virtual ICollection<film_table> film_table { get; set; }
    }
}
