//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photos_table
    {
        public photos_table()
        {
            this.film_table = new HashSet<film_table>();
        }
    
        public int id_photo { get; set; }
        public string photo_url { get; set; }
    
        public virtual ICollection<film_table> film_table { get; set; }
    }
}
