//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producer_table
    {
        public int id_film { get; set; }
        public string producer_name { get; set; }
        public string producer_surname { get; set; }
    
        public virtual film_table film_table { get; set; }
    }
}
