//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class actor_table
    {
        public actor_table()
        {
            this.actor_film_table = new HashSet<actor_film_table>();
        }
    
        public int id_actor { get; set; }
        public string actor_name { get; set; }
        public string actor_surname { get; set; }
        public string actor_photo_url { get; set; }
    
        public virtual ICollection<actor_film_table> actor_film_table { get; set; }
    }
}
