//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class actor_film_table
    {
        public int id_film { get; set; }
        public int id_actor { get; set; }
    
        public virtual actor_table actor_table { get; set; }
        public virtual film_table film_table { get; set; }
    }
}
