//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBayMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class film_table
    {
        public film_table()
        {
            this.actor_film_table = new HashSet<actor_film_table>();
            this.comment_table = new HashSet<comment_table>();
            this.producer_table = new HashSet<producer_table>();
            this.vote_table = new HashSet<vote_table>();
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.AspNetUsers1 = new HashSet<AspNetUsers>();
            this.genere_table = new HashSet<genere_table>();
            this.music_creator_table = new HashSet<music_creator_table>();
            this.other_language_table = new HashSet<other_language_table>();
            this.photos_table = new HashSet<photos_table>();
            this.writers_table = new HashSet<writers_table>();
        }
    
        public int id_film { get; set; }
        public string title { get; set; }
        public string title_orginal { get; set; }
        public System.TimeSpan duration { get; set; }
        public string director_name { get; set; }
        public string director_surname { get; set; }
        public Nullable<int> age_restriction { get; set; }
        public string publisher { get; set; }
        public string storyline { get; set; }
        public string orginal_language { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> nuber_of_votes { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public double film_price { get; set; }
        public string film_studio { get; set; }
        public string poster_url { get; set; }
    
        public virtual ICollection<actor_film_table> actor_film_table { get; set; }
        public virtual ICollection<comment_table> comment_table { get; set; }
        public virtual ICollection<producer_table> producer_table { get; set; }
        public virtual ICollection<vote_table> vote_table { get; set; }
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        public virtual ICollection<AspNetUsers> AspNetUsers1 { get; set; }
        public virtual ICollection<genere_table> genere_table { get; set; }
        public virtual ICollection<music_creator_table> music_creator_table { get; set; }
        public virtual ICollection<other_language_table> other_language_table { get; set; }
        public virtual ICollection<photos_table> photos_table { get; set; }
        public virtual ICollection<writers_table> writers_table { get; set; }
    }
}
