<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-FilmBayMVC-20150104082632" Class="MyLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\aspnet-FilmBayMVC-20150104082632.mdf;Initial Catalog=aspnet-FilmBayMVC-20150104082632;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnet_FilmBayMVC_20150104082632ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.actor_film_table" Member="actor_film_tables">
    <Type Name="actor_film_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_actor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="actor_table_actor_film_table" Member="actor_table" ThisKey="id_film" OtherKey="id_actor" Type="actor_table" IsForeignKey="true" />
      <Association Name="film_table_actor_film_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.writers_table" Member="writers_tables">
    <Type Name="writers_table">
      <Column Name="id_writer" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="writer_name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="writer_surname" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="writers_table_film_writers_table" Member="film_writers_tables" ThisKey="id_writer" OtherKey="id_writer" Type="film_writers_table" />
    </Type>
  </Table>
  <Table Name="dbo.actor_table" Member="actor_tables">
    <Type Name="actor_table">
      <Column Name="id_actor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="actor_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="actor_surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="actor_photo_url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="actor_table_actor_film_table" Member="actor_film_tables" ThisKey="id_actor" OtherKey="id_film" Type="actor_film_table" />
    </Type>
  </Table>
  <Table Name="dbo.admin_table" Member="admin_tables">
    <Type Name="admin_table">
      <Column Name="id_admin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="e_mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="is_admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
      <Association Name="AspNetUser_bought_films_table" Member="bought_films_tables" ThisKey="Id" OtherKey="id" Type="bought_films_table" />
      <Association Name="AspNetUser_comment_table" Member="comment_tables" ThisKey="Id" OtherKey="id" Type="comment_table" />
      <Association Name="AspNetUser_favourites_films_table" Member="favourites_films_tables" ThisKey="Id" OtherKey="id" Type="favourites_films_table" />
      <Association Name="AspNetUser_vote_table" Member="vote_tables" ThisKey="Id" OtherKey="id" Type="vote_table" />
    </Type>
  </Table>
  <Table Name="dbo.bought_films_table" Member="bought_films_tables">
    <Type Name="bought_films_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_bought_films_table" Member="AspNetUser" ThisKey="id" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
      <Association Name="film_table_bought_films_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.comment_table" Member="comment_tables">
    <Type Name="comment_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_comment_table" Member="AspNetUser" ThisKey="id" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
      <Association Name="film_table_comment_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.favourites_films_table" Member="favourites_films_tables">
    <Type Name="favourites_films_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_favourites_films_table" Member="AspNetUser" ThisKey="id" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
      <Association Name="film_table_favourites_films_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.film_genere_table" Member="film_genere_tables">
    <Type Name="film_genere_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_genere" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="film_table_film_genere_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
      <Association Name="genere_table_film_genere_table" Member="genere_table" ThisKey="id_genere" OtherKey="id_genere" Type="genere_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.film_music_creators" Member="film_music_creators">
    <Type Name="film_music_creator">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_music_creator" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="film_table_film_music_creator" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
      <Association Name="music_creator_table_film_music_creator" Member="music_creator_table" ThisKey="id_music_creator" OtherKey="id_music_creator" Type="music_creator_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.film_other_language_table" Member="film_other_language_tables">
    <Type Name="film_other_language_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_other_language" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="film_table_film_other_language_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
      <Association Name="other_language_table_film_other_language_table" Member="other_language_table" ThisKey="id_other_language" OtherKey="id_other_language" Type="other_language_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.film_photos_table" Member="film_photos_tables">
    <Type Name="film_photos_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_photo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="film_table_film_photos_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
      <Association Name="photos_table_film_photos_table" Member="photos_table" ThisKey="id_photo" OtherKey="id_photo" Type="photos_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.film_table" Member="film_tables">
    <Type Name="film_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="title_orginal" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="duration" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="director_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="director_surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="age_restriction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publisher" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="storyline" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="orginal_language" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rating" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nuber_of_votes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="release_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="film_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="film_studio" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="poster_url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="film_table_actor_film_table" Member="actor_film_tables" ThisKey="id_film" OtherKey="id_film" Type="actor_film_table" />
      <Association Name="film_table_bought_films_table" Member="bought_films_tables" ThisKey="id_film" OtherKey="id_film" Type="bought_films_table" />
      <Association Name="film_table_comment_table" Member="comment_tables" ThisKey="id_film" OtherKey="id_film" Type="comment_table" />
      <Association Name="film_table_favourites_films_table" Member="favourites_films_tables" ThisKey="id_film" OtherKey="id_film" Type="favourites_films_table" />
      <Association Name="film_table_film_genere_table" Member="film_genere_tables" ThisKey="id_film" OtherKey="id_film" Type="film_genere_table" />
      <Association Name="film_table_film_music_creator" Member="film_music_creators" ThisKey="id_film" OtherKey="id_film" Type="film_music_creator" />
      <Association Name="film_table_film_other_language_table" Member="film_other_language_tables" ThisKey="id_film" OtherKey="id_film" Type="film_other_language_table" />
      <Association Name="film_table_film_photos_table" Member="film_photos_tables" ThisKey="id_film" OtherKey="id_film" Type="film_photos_table" />
      <Association Name="film_table_film_writers_table" Member="film_writers_tables" ThisKey="id_film" OtherKey="id_film" Type="film_writers_table" />
      <Association Name="film_table_producer_table" Member="producer_tables" ThisKey="id_film" OtherKey="id_film" Type="producer_table" />
      <Association Name="film_table_vote_table" Member="vote_tables" ThisKey="id_film" OtherKey="id_film" Type="vote_table" />
    </Type>
  </Table>
  <Table Name="dbo.film_writers_table" Member="film_writers_tables">
    <Type Name="film_writers_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_writer" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="film_table_film_writers_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
      <Association Name="writers_table_film_writers_table" Member="writers_table" ThisKey="id_writer" OtherKey="id_writer" Type="writers_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.genere_table" Member="genere_tables">
    <Type Name="genere_table">
      <Column Name="id_genere" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="genere_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="genere_table_film_genere_table" Member="film_genere_tables" ThisKey="id_genere" OtherKey="id_genere" Type="film_genere_table" />
    </Type>
  </Table>
  <Table Name="dbo.music_creator_table" Member="music_creator_tables">
    <Type Name="music_creator_table">
      <Column Name="id_music_creator" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="music_creator_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="music_creator_surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="music_creator_table_film_music_creator" Member="film_music_creators" ThisKey="id_music_creator" OtherKey="id_music_creator" Type="film_music_creator" />
    </Type>
  </Table>
  <Table Name="dbo.other_language_table" Member="other_language_tables">
    <Type Name="other_language_table">
      <Column Name="id_other_language" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="other_language_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="other_language_table_film_other_language_table" Member="film_other_language_tables" ThisKey="id_other_language" OtherKey="id_other_language" Type="film_other_language_table" />
    </Type>
  </Table>
  <Table Name="dbo.photos_table" Member="photos_tables">
    <Type Name="photos_table">
      <Column Name="id_photo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="photo_url" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="photos_table_film_photos_table" Member="film_photos_tables" ThisKey="id_photo" OtherKey="id_photo" Type="film_photos_table" />
    </Type>
  </Table>
  <Table Name="dbo.producer_table" Member="producer_tables">
    <Type Name="producer_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="producer_name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="producer_surname" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="film_table_producer_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_table" Member="user_tables">
    <Type Name="user_table">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="e_mail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="is_admin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vote_table" Member="vote_tables">
    <Type Name="vote_table">
      <Column Name="id_film" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vote" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_vote_table" Member="AspNetUser" ThisKey="id" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
      <Association Name="film_table_vote_table" Member="film_table" ThisKey="id_film" OtherKey="id_film" Type="film_table" IsForeignKey="true" />
    </Type>
  </Table>
</Database>